### PR TITLE
feat: added support for terraform init upgrade flag

### PR DESCRIPTION
**Pull request by janritter**

### CODE REVIEW

**Comment by vatima2016** [comment]
Successfully tested:
- export TERRASTATE_TF_INIT_UPGRADE=True; terrastateLocal apply --var-file=../vars/qa-sso-ts.tfvars
- $HOME/.terrastate.yaml; terrastateLocal apply --var-file=../vars/qa-sso-ts.tfvars
- terrastateLocal apply --var-file=../vars/qa-sso-ts.tfvars --terrastate-file=.terrastate.yaml

This did not work for me:
terrastateLocal apply --tf-init-upgrade=True --var-file=../vars/qa-sso-ts.tfvars
terrastateLocal apply --tf-init-upgrade=true --var-file=../vars/qa-sso-ts.tfvars
terrastateLocal apply --tf-init-upgrade --var-file=../vars/qa-sso-ts.tfvars

**Comment by janritter** [comment]
@vatima2016 @timo-reymann please test again

**Review by vatima2016 — APPROVED** [review]
it works for me now

**Pull request merged**
